### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by razbensimon** [GuyGooL5/zoom-o-matic#1]
![image](https://user-images.githubusercontent.com/5955905/111213919-f6350780-85d9-11eb-82b8-3d2669c406f7.png)

My user and pass is correct ...

**Comment by GuyGooL5** [comment]
Is that the official website or a static setup, and also please include browser + version so i'll try recreating the problem.
For me in Edge 89.0.774.54 it works fine.

**Comment by razbensimon** [comment]
What do you mean static setup? 

Chrome 89

**Comment by GuyGooL5** [comment]
I meant locally. Sorry.

**Comment by razbensimon** [comment]
It is the official website

**Comment by GuyGooL5** [comment]
I might know why it happens, did you use the username with which you signed up on HIT or your ID?
Because it doesn't work with the username, only with ID (just like the official Moodle app)

**Comment by razbensimon** [comment]
used my username, should i try with ID?

**Comment by GuyGooL5** [comment]
Yes it doesn't work with usernames (it's an HIT issue, the login there is ambiguous).

**Comment by razbensimon** [comment]
Cool, login succeeds.
Now I am trying to understand the app, the zoom menu looks the same as the zoom in moodle. so what is the added value?

**Comment by GuyGooL5** [comment]
Every zoom link is displayed in one screen instead of going to different courses. That's pretty simplistic. Currently not much, maybe in the future I'll expand it. Closing Issue 😎 .
